production:
  clients:
    default:
     uri: mongodb://root:root@ds017231.mlab.com:17231/parse_server_sarkar
     options:
       connect_timeout: 15

development:
  clients:
    default:
     uri: mongodb://root:root@ds017231.mlab.com:17231/parse_server_sarkar
     options:
       connect_timeout: 15